spring:
    datasource:
        name: test
        url: jdbc:mysql://rm-uf68jd8ruq3zl57h4eo.mysql.rds.aliyuncs.com:3306/qibing
        username: root
        password: Jiuying2018
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 2000
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  #实体类所做包
  type-aliases-package: com.nineShadow.model
  #mapper.xml所在位置
  mapper-locations: com/nineShadow/mapper/*.xml        
